# -*- coding: utf-8 -*-
"""linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JTxVnjnY8E1d8CEYWkpu5msvDcPMcxe
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

data=  pd.read_csv("Salary_dataset.csv")

data

data["YearsExperience"]

data.head(10)

data.info()

data.shape

data.describe()

data.describe().T

data['YearsExperience'].value_counts()

data.isnull().sum()

data.duplicated()

data.duplicated().sum()

from sklearn.model_selection import train_test_split

x = data.iloc[:,:-1]
y = data.iloc[:,-1]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

x_train.shape

x_test.shape

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr = lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mse = mean_squared_error(y_test,y_pred)

mae = mean_absolute_error(y_test,y_pred)

r2 = r2_score(y_test,y_pred)

r2

f"my modelperformance is {r2} and its meansquared error is {mse} and its mean absolute error is {mae}"

